theme: jekyll-theme-minimal
title: Dylan Lynch
logo: ![head shot]https://github.com/dylanomics/dylanomics.github.io/blob/main/Headshot.jpg 
description: Senior Program Analyst at Cape Henry Associates, Inc.
github:
  is_project_page: false
