theme: jekyll-theme-minimal
title: Dylan Lynch
![head shot]https://github.com/dylanomics/dylanomics.github.io/blob/main/Headshot.jpg 
description: Senior Program Analyst at Cape Henry Associates, Inc.
logo: https://static.www.nfl.com/t_q-best/league/api/clubs/logos/TB
github:
  is_project_page: false
