theme: jekyll-theme-minimal
title: Dylan Lynch
logo: ![Headshot](https://user-images.githubusercontent.com/98568281/155864678-6702fe69-d4e5-4d77-8804-f7fa6be58842.jpg)
description: Senior Program Analyst at Cape Henry Associates, Inc.
github:
  is_project_page: false
